#pragma once

enum CanProtocolPortID {
    ROBOT_CURRENT_STATE_ID = 1,
    ROBOT_POSE_GOAL_ID,
    ROBOT_TWIST_GOAL_ID,
    ROBOT_SET_CURRENT_POSE_ID,

    MOTION_SET_PID_ID,
    MOTION_SET_ADAPTATIVE_PID_ID,
    MOTION_SET_MOTION_CONFIG_ID,
    MOTION_PID_STATE_ID,
    MOTION_RESET_ID,

    EMERGENCY_STATE_ID,

    ACTION_SERVO_SET_ANGLE_ID,
    ACTION_SERVO_SET_CONFIG_ID,
    ACTION_SERVO_SET_COLOR_ID,
    ACTION_SLIDER_SET_POSITION_ID,
    ACTION_SLIDER_SET_CONFIG_ID,
    ACTION_PUMP_SET_STATUS_ID,
    ACTION_PUMP_STATUS_ID,
    ACTION_VALVE_SET_STATUS_ID,
    ACTION_VALVE_STATUS_ID,

};

enum CanProtocolNodeID {
    CAN_PROTOCOL_EMBEDDED_COMPUTER_ID = 42, // the answer
    CAN_PROTOCOL_MOTION_BOARD_ID      = 11, // the legs
    CAN_PROTOCOL_ACTION_BOARD_ID      = 31, // 11 + 31 = 42 !!
};

enum CanProtocolServoID {
    CAN_PROTOCOL_SERVO_ARM_LEFT_A,
    CAN_PROTOCOL_SERVO_ARM_LEFT_B,
    CAN_PROTOCOL_SERVO_ARM_LEFT_C,
    CAN_PROTOCOL_SERVO_ARM_LEFT_D,
    CAN_PROTOCOL_SERVO_ARM_LEFT_E,
    CAN_PROTOCOL_SERVO_ARM_RIGHT_A,
    CAN_PROTOCOL_SERVO_ARM_RIGHT_B,
    CAN_PROTOCOL_SERVO_ARM_RIGHT_C,
    CAN_PROTOCOL_SERVO_ARM_RIGHT_D,
    CAN_PROTOCOL_SERVO_ARM_RIGHT_E,
};

enum CanProtocolSliderID {
    CAN_PROTOCOL_SLIDER_LEFT,
    CAN_PROTOCOL_SLIDER_RIGHT,
};
